### ISSUE TITLE
Consistency issue

### ISSUE THREAD

**Issue by 2-towns** [semarketir/quranjson#29]
As salam alaykoum, 

Surah Al Baqarah doesn't contain the audio file for "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيم" but Al 'Imran does contain it.

**Comment by semarketir** [comment]
'alaikumsalam

hi @arnaud-zad 
I just updated & reformatted audio files https://github.com/semarketir/quranjson/pull/30

I will close this issue

thank you 🙇‍♂️
