### ISSUE TITLE
Tajwid

### ISSUE THREAD

**Issue by semarketir** [semarketir/quranjson#5]
Melengkapi hukum tanda baca disetiap Ayat.

**Comment by 2-towns** [comment]
How do you want to achieve this ? HTML or images ?

**Comment by semarketir** [comment]
hi @arnaud-zad 

regarding tajweed, I wanted to do like this, e.g:
```
{
    "index": "001",
    "name": "al-Fatihah",
    "verse": {
        "verse_1": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        ...
    },
    ...
}
```

then each surah will has tajweed files that contains, e.g ( `source/tajweed/surah_1.json` ):
```
{
  "index": "001",
  "verse": {
    "verse_1": {
        // specified index in string
        "start": 9,
        "end": 10,
        "rules": [
            // actualy I wanted to put rule types here
            // e.g: IDGHAM_SYAMSI_BILA_GHUNNAH
            "Idgham Syamsi Bila Ghunnah",
            "Mad Asli Mutlak",
            "Lam dibaca nipis"
        ]
    },
    ...
  },
  "count": 7
}
```


refs:
![01](https://user-images.githubusercontent.com/1286932/54257853-4c0de980-4593-11e9-9cf5-b28e6660b51c.JPG)
```
7 - Idgham Syamsi Bila Ghunnah
16 - Mad Asli Mutlak
19 - Mad Arid Lissukun
31 - Ro dibaca tebal
34 - Lam dibaca nipis
```

what do you think with this one?

**Comment by 2-towns** [comment]
It's already existing : https://github.com/cpfair/quran-tajweed

**Comment by semarketir** [comment]
@arnaud-zad awesome ! thanks a lot ! 
I will try to adjust the output from `cpfair/quran-tajweed` with `quranjson`
