### ISSUE TITLE
A Separator for بِسْمِ اللّهِ الرَّحْمَنِ الرَّحِيْمِ

### ISSUE THREAD

**Issue by semarketir** [semarketir/quranjson#6]
Memisahkan بِسْمِ اللّهِ الرَّحْمَنِ الرَّحِيْمِ dengan suatu divider, supaya tidak terkesan menyambung dengan ayat yg lain didalam surah.

i.e :
[ Q.S : Al-Baqarah ]
{
..
"verse_1": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ",
..
}

Bener ya @Keda87 ?? بِسْمِ اللّهِ الرَّحْمَنِ الرَّحِيْمِ rada sedikit kaya nyambung, mesti pake divider yg lain buat misahinnya ~

**Comment by Keda87** [comment]
Btw itu بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ apa mau dihapus aja apa gimana mas dari **بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ** الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ ? agak bingung mau dikasih dividernya apa 😅

**Comment by semarketir** [comment]
@Keda87 hahaha jangan dihapus sih keknya di, mending dipikirin buat dikasih kaya semacam separate gitu hahaha
Ntar kalau ada ide, kasih tau aja, hahaha

**Comment by Keda87** [comment]
kalo semisal begini gimana mas?

`بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ) الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ )`
`بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ } الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ }`
`بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ | الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ`

**Comment by ghost** [comment]
Buat mayoritas programmer, biar nge-regex lebih mudah biasa pake yg mana di? haha

Btw, buat separator pake branch ini [features/separate](https://github.com/semarketir/quranjson/tree/features/separate) biar kek serius dikit wkwkwk

**Comment by Keda87** [comment]
gak pernah coba sih regex buat arabic gini 😁 , tapi menurutku `(` `)` lebih readable cuman kalo di regex jadi susah ntar dikira grouping. belum coba sih 😅

**Comment by semarketir** [comment]
@Keda87 Ok pake  `(` `)` aja nyak wkwkwk

**Comment by semarketir** [comment]
{
    "index": "114",
    "name": "an-Nas",
    "verse": {
        "verse_0": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "verse_1": "قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
        "verse_2": "مَلِكِ النَّاسِ",
        "verse_3": "إِلَٰهِ النَّاسِ",
        "verse_4": "مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ",
        "verse_5": "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ",
        "verse_6": "مِنَ الْجِنَّةِ وَالنَّاسِ"
    },
    "count": 6
}
